- name: playbook1
  hosts: localhost
  tasks:
    - name: create user
      user:
        name: manas
        state: present

    - name: install package
      apt:
        name: httpd
        state: present

    - name: start the service
      service:
        name: httpd
        state: started
        enable: true
